---
title: "CFA_project"
author: "Allama Ikbal Sijan"
date: "2024-11-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages

```{r packages upload, message=FALSE, warning=FALSE}
library(tidyverse)
library(psych)
library(lavaan)
library(semTools)
library(GPArotation)
library(haven)
library(stringr)
```

## Data Cleaning

```{r loading data, warning=FALSE}
df <- read_sav("discounting_data.sav")

# Any incomplete data
df %>% 
  group_by(Finished) %>% 
  count()

# only relevant variable
df <- df %>% 
  select(c("ResponseId", starts_with("defer"), starts_with("expedite")))

# 3 incomplete rows but did they complete the discounting task?
na_count <- function(df){
  na_dict <- list()
  
  for (var in colnames(df)){
    total_na <- sum(is.na(df$var))
    na_dict[[var]] = total_na
  }
    
  return(na_dict)
}

print(unlist(na_count(df)))

# All 500 data points have complete data on the discounting tasks
```

```{r}
class(df$defer1) # interestingly the discounting items are character types when they should be numeric

# identifying the participants that used `$` sign
set_dolla_sign <- list()

for (var in names(df)){
  index_vec <- str_which(df[[var]], "^\\$")
  for (vec in index_vec) {
    set_dolla_sign <- union(set_dolla_sign, vec)
  }
}

print(unlist(set_dolla_sign))
```
```{r}
# removing the $ sign from individual responses
df <- data.frame(lapply(df, function(x) str_remove(x, "^\\$")))

# checking if the function worked
str_which(df$defer1, "^\\$")

# removing the (,) from individual responses as that coerces the value to be NA
df <- data.frame(lapply(df, function(x) str_remove_all(x, ",")))

# also noticed some instances of (.) at the end of the data which coerces into NAs, thus removing those as well
df <- data.frame(lapply(df, function(x) str_remove(x, "\\.+$")))
```

```{r, warning=FALSE}
# detecting index of text responses (that will be converted to NAs)
text_NAs <- list()

for (var in df %>% select(-ResponseId) %>% names()){
  index_vec <- str_which(df[[var]], "[^0-9.]")
  for (index in index_vec){
    text_NAs <- union(text_NAs, index)
  }
}

print(unlist(text_NAs))

# Character to Numeric
new_df <- data.frame(lapply(df[, -which(names(df) == "ResponseId")], as.numeric))
new_df <- new_df %>% 
  add_column(df$ResponseId, .before = 1) %>% 
  rename(ResponseId = `df$ResponseId`)
```

# Converting Responses to Discount Rates

```{r}
df <- new_df

df <- df %>% 
  mutate(dr_defer1 = (log(defer1 / 40)) / (1/12),
         dr_defer2 = (log(defer2 / 1500)) / (12/12),
         dr_defer3 = (log(defer3 / 75)) / (6/12),
         dr_defer4 = (log(defer4 / 800)) / (1/12),
         dr_defer5 = (log(defer5 / 1250)) / (6/12),
         dr_defer6 = (log(defer6 / 50)) / (12/12),
         dr_expedite1 = (log(40 / expedite1)) / (1/12),
         dr_expedite2 = (log(1500 / expedite2)) / (12/12),
         dr_expedite3 = (log(75 / expedite3)) / (6/12),
         dr_expedite4 = (log(800 / expedite4)) / (1/12),
         dr_expedite5 = (log(1250 / expedite5)) / (6/12),
         dr_expedite6 = (log(50 / expedite6)) / (12/12),
         )

```

```{r, eval=FALSE}
str_which(df$defer3, "^\\$")
test_df <- data.frame(a = 1:3, b = 4:6)
test_df

# Apply to each value in each column
new_df <- data.frame(apply(test_df, 2, function(x) x * 2)) 
data.frame(lapply(test_df, function(x) x* 2))

# row-wise operations
apply(test_df, 1, function(x) sum(x)) 
data.frame(sapply(test_df, function(x) x* 2))
```

